Us5003 add students submit request
Dragan14/ken pull request #27
Opened 2023-10-03 00:35 UTC by Stefce02

2023-10-03 10:32 UTC, yujlin2 approved these changes
Nice

2023-10-10 05:04 UTC, Dragan14 requested changes

2023-10-10 06:24 UTC, Stefce02 commented on src/hooks/useGroupsInCourse.tsx
Fixed in bb2b06472d04ea9121bee3e4963a9e65b2ea69cf

2023-10-10 06:24 UTC, Stefce02 commented on src/hooks/useSelfGroups.tsx
Fixed in bb2b06472d04ea9121bee3e4963a9e65b2ea69cf

2023-10-10 06:24 UTC, Stefce02 commented on src/hooks/useUsersInGroup.tsx
Fixed in bb2b06472d04ea9121bee3e4963a9e65b2ea69cf

2023-10-10 07:09 UTC, Dragan14 approved these changes
lgtm

2023-10-10 07:09 UTC, merged