US6008   settings backend
Dragan14/ken pull request #56
Opened 2023-10-31 12:14 UTC by yujlin2

Integration

2023-11-03 10:26 UTC, Stefce02 requested changes
Aside from the comments their is one main issue:
- None of the requests show if the staff member is not allowed to add requests for even just  one assignment

I would also like to see:
- the setting be a radio button rather than checkbox: "allow all tutors to accept requests for this assignment?" - YES/NO. This should then remain ticked based on the user selection. If YES, the next time they go to it, it should still show YES. This button should also not show until the user has selected the assignment.
- Another change is to hide this setting tab all together for any staff member that is not TeacherEnrollment as it doesn't make sense for them to be able to see it as they are not the coordinator

2023-11-03 10:26 UTC, Stefce02 commented on src/components/AssignmentSettings.tsx
> +										enrollment.role === "TeacherEnrollment"
Add comment to say that we're assuming subject coord will have TeachEnrollment. Can be changed to suit name of role in actual Canvas instance. Could make it a var in the env file

2023-11-03 10:38 UTC, yujlin2 commented on src/components/StaffViewRequests.tsx
> +													"TeacherEnrollment" ||
I changed this because the TaEnrollment also satisfy this condition which would be incorrect.

2023-11-08 11:43 UTC, Dragan14 approved these changes
👍

2023-11-08 11:49 UTC, merged